# Generated by Django 3.0.5 on 2020-04-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.CharField(max_length=24, unique=True)),
                ('address', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('expire', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='food_tickets.Store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTicketHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_hours', to='food_tickets.Store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='food_tickets.Store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_tickets.StoreArea'),
        ),
        migrations.AddField(
            model_name='store',
            name='genres',
            field=models.ManyToManyField(to='food_tickets.StoreGenre'),
        ),
    ]
